# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827dac5f2493e30862473dcbbe798d2c88ec219d77dbd399852d21792f5b9d436c192da7d07fc1182a95b54f262c670c03127a49228667226162511fec722e06

test:
  secret_key_base: c99159f71e3f74900135bd254acb13c422d23670ef4b6cfb0e646498564a9bd4d7fc747e1687f56a2619b0c7ca9d1f5085b2e661aef326c2280681ccf3c766d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
